name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Show Python version
      run: python --version
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install databricks-sql requests pyinstaller
        
    - name: Test import
      run: |
        python -c "from databricks import sql; print('Import successful')"
        
    - name: List files
      run: |
        dir
        dir *.py
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Creative_Pull_UI" creative_previewer_app_webview.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Creative_Pull_UI_Windows
        path: dist/Creative_Pull_UI.exe
